### ISSUE TITLE
Error on import

### ISSUE THREAD

**Issue by eugenio11** [camel1cz/phorum2phpbb#3]
Hi,
I am trying to convert a phorum 5.2.22 installation to a phpBB 3.3.5.
This is the error I get during the conversion:

Fatal error: Uncaught Error: Class name must be a valid object or a string in /mypath/phpbb/install/convert/convertor.php:134 Stack trace: #0 /mypath/phpbb/install/convert/controller/convertor.php(370): phpbb\convert\convertor->convert_data('phorum5') #1 /mypath/phpbb/vendor/symfony/http-kernel/HttpKernel.php(151): phpbb\convert\controller\convertor->convert('phorum5') #2 /mypath/phpbb/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(phpbb\symfony_request), 1) #3 /mypath/phpbb/install/app.php(61): Symfony\Component\HttpKernel\HttpKernel->handle(Object(phpbb\symfony_request)) #4 {main} thrown in /mypath/phpbb/install/convert/convertor.php on line 134

Any idea?

Thanks!

**Comment by eugenio11** [comment]
Please ignore the comment, after a few tries the error disappeared.
